name: Print nama

on:
  push:
    branches:
      - main

jobs:
  run_print_nama:
    name: Run print_nama.py
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Ubah jika menggunakan versi Python yang berbeda

    - name: Run print_nama.py
      run: python print_nama.py
