print ("Nama Kelompok Jakarta")
print("1. Handika Juan Putra Sinaga")
print("2. Marjuenz Henry Suparto")
print("3. Ariq Azmi Lubis")
print("4. Ahnaf Musyaffa Bisyri Hendro Subagio")
print("5. Arif Fadillah")
print("6. Mila Lestari")
print("7. Beni Ardiyanto")
print("8. Kirana Andriyani")
print("9. Muhammad Rayhan Denzuko")
print("10. Satya Ananta Azis")
print("11. Fransiscus Dharma Hadi Prayoga")
print("12. Muhammad Faruoq Siswanto")
print("13. Ari Purnomo Aji")
print("14. Aisah")
print("15. Jihan Hakima")
print("16. Muhammad Farrel Daviaziz")
print("17. Dhita Hartanti Octavia")
print("18. Ahmad Raihan Asyam")
print("19. Fernanda S")
print("20. Sendi Alhazen Mulyono")
